language: python
notifications:
  email: false
python:
  - "3.6"
before_script:
  - sudo apt-get install libcr-dev mpich2 mpich2-doc
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install xtal
  - pip install mpi4py
  - pip install platypus-opt
script:
  - cd tests
  - pytest -v
